services:
  backend:
    image: temz21/group3-2tier-node-temz21:backend-latest
    ports:
      - "5000:5000"

  frontend:
    image: temz21/group3-2tier-node-temz21:frontend-latest
    ports:
      - "80:80"
